// Lingke Coding Models Configuration
// This file defines the models available through the Lingke API
import type * as ModelsDev from "../schema/models-dev"

export const lingkeModelsProvider: ModelsDev.Provider = {
  id: "lingke",
  name: "Lingke Coding",
  api: "https://api.lingke.ink",
  env: ["LINGKE_API_KEY"],
  models: {
    // Kimi Models
    "moonshotai/Kimi-K2-Instruct-0905": {
      id: "moonshotai/Kimi-K2-Instruct-0905",
      name: "Kimi K2 (0905)",
      family: "moonshotai",
      cost: { input: 1.5, output: 1.5 },
      limit: { context: 128000, input: 128000, output: 8192 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    // GLM Models
    "Pro/zai-org/GLM-4.7": {
      id: "Pro/zai-org/GLM-4.7",
      name: "GLM-4.7",
      family: "glm",
      cost: { input: 0.5, output: 0.5 },
      limit: { context: 128000, input: 128000, output: 8192 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    // Qwen Models
    "Qwen/Qwen3-14B": {
      id: "Qwen/Qwen3-14B",
      name: "Qwen3 14B",
      family: "qwen",
      cost: { input: 0.8, output: 0.8 },
      limit: { context: 32000, input: 32000, output: 4096 },
      temperature: true,
      reasoning: false,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    // GPT Models
    "gpt-5.4-mini-ca": {
      id: "gpt-5.4-mini-ca",
      name: "GPT-5.4 Mini CA",
      family: "openai",
      cost: {
        input: 0.9,
        output: 3.6,
        cache_read: 0.45,
      },
      limit: { context: 128000, input: 128000, output: 16384 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text", "image"], output: ["text"] },
    },
    "gpt-3.5-turbo": {
      id: "gpt-3.5-turbo",
      name: "GPT-3.5 Turbo",
      family: "openai",
      cost: { input: 0.5, output: 1.5 },
      limit: { context: 16385, input: 16385, output: 4096 },
      temperature: true,
      reasoning: false,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text", "image"], output: ["text"] },
    },
    // DeepSeek Models
    "deepseek-v4-pro": {
      id: "deepseek-v4-pro",
      name: "DeepSeek V4 Pro",
      family: "deepseek",
      cost: {
        input: 1.0,
        output: 4.0,
        cache_read: 0.5,
      },
      limit: { context: 64000, input: 64000, output: 8192 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    "deepseek-v4-flash": {
      id: "deepseek-v4-flash",
      name: "DeepSeek V4 Flash",
      family: "deepseek",
      cost: {
        input: 0.5,
        output: 2.0,
        cache_read: 0.25,
      },
      limit: { context: 64000, input: 64000, output: 8192 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    "deepseek-r1-0528": {
      id: "deepseek-r1-0528",
      name: "DeepSeek R1 (0528)",
      family: "deepseek",
      cost: { input: 0.6, output: 2.4 },
      limit: { context: 64000, input: 64000, output: 8192 },
      temperature: false,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    "deepseek-ai/DeepSeek-V3.2": {
      id: "deepseek-ai/DeepSeek-V3.2",
      name: "DeepSeek V3.2",
      family: "deepseek",
      cost: {
        input: 0.5,
        output: 2.0,
        cache_read: 0.25,
      },
      limit: { context: 64000, input: 64000, output: 8192 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
    "deepseek-ai/DeepSeek-V3.1-Terminus": {
      id: "deepseek-ai/DeepSeek-V3.1-Terminus",
      name: "DeepSeek V3.1 Terminus",
      family: "deepseek",
      cost: {
        input: 0.4,
        output: 1.6,
        cache_read: 0.2,
      },
      limit: { context: 64000, input: 64000, output: 8192 },
      temperature: true,
      reasoning: true,
      attachment: true,
      tool_call: true,
      modalities: { input: ["text"], output: ["text"] },
    },
  },
}

export const lingkeProvider = lingkeModelsProvider
